// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: about.sql

package database

import (
	"context"
)

const getAboutRevision = `-- name: GetAboutRevision :one
SELECT id, body, created_at FROM about_revision WHERE id = $1
`

func (q *Queries) GetAboutRevision(ctx context.Context, id int64) (AboutRevision, error) {
	row := q.db.QueryRow(ctx, getAboutRevision, id)
	var i AboutRevision
	err := row.Scan(&i.ID, &i.Body, &i.CreatedAt)
	return i, err
}

const getLatestAboutRevision = `-- name: GetLatestAboutRevision :one
SELECT id, body, created_at FROM about_revision ORDER BY created_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLatestAboutRevision(ctx context.Context) (AboutRevision, error) {
	row := q.db.QueryRow(ctx, getLatestAboutRevision)
	var i AboutRevision
	err := row.Scan(&i.ID, &i.Body, &i.CreatedAt)
	return i, err
}

const insertAboutRevision = `-- name: InsertAboutRevision :one
INSERT INTO about_revision (body) VALUES ($1) RETURNING id, body, created_at
`

// Insert-only: the About page's content is never overwritten, only ever
// superseded by a newer row. Restoring an old revision is just another
// insert of that old body, not a separate operation — see
// docs/adr/0009-about-page-db-backed-with-revision-history.md.
func (q *Queries) InsertAboutRevision(ctx context.Context, body string) (AboutRevision, error) {
	row := q.db.QueryRow(ctx, insertAboutRevision, body)
	var i AboutRevision
	err := row.Scan(&i.ID, &i.Body, &i.CreatedAt)
	return i, err
}

const listAboutRevisions = `-- name: ListAboutRevisions :many
SELECT id, body, created_at FROM about_revision ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAboutRevisions(ctx context.Context) ([]AboutRevision, error) {
	rows, err := q.db.Query(ctx, listAboutRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AboutRevision
	for rows.Next() {
		var i AboutRevision
		if err := rows.Scan(&i.ID, &i.Body, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
