// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID           int64
	Title        string
	Slug         string
	Body         string
	SoWhat       string
	Tags         []string
	Version      int32
	PublishedAt  pgtype.Timestamptz
	FeaturedRank pgtype.Int4
}

type PostProject struct {
	PostID    int64
	ProjectID int64
}

type Project struct {
	ID           int64
	Name         string
	Slug         string
	Description  string
	FeaturedRank pgtype.Int4
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}
