// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFeaturedPosts = `-- name: ClearFeaturedPosts :exec
UPDATE posts SET featured_rank = NULL WHERE featured_rank IS NOT NULL
`

func (q *Queries) ClearFeaturedPosts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearFeaturedPosts)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, title, slug, body, so_what, tags, version, published_at, featured_rank FROM posts WHERE slug = $1
`

func (q *Queries) GetPost(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.SoWhat,
		&i.Tags,
		&i.Version,
		&i.PublishedAt,
		&i.FeaturedRank,
	)
	return i, err
}

const insertPost = `-- name: InsertPost :one
INSERT INTO posts (title, slug, body, so_what, tags, published_at)
VALUES ($1, $2, $3, $4, $5, COALESCE($6::timestamptz, now()))
RETURNING id, title, slug, body, so_what, tags, version, published_at, featured_rank
`

type InsertPostParams struct {
	Title       string
	Slug        string
	Body        string
	SoWhat      string
	Tags        []string
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, insertPost,
		arg.Title,
		arg.Slug,
		arg.Body,
		arg.SoWhat,
		arg.Tags,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.SoWhat,
		&i.Tags,
		&i.Version,
		&i.PublishedAt,
		&i.FeaturedRank,
	)
	return i, err
}

const listFeaturedPosts = `-- name: ListFeaturedPosts :many
SELECT id, title, slug, body, so_what, tags, version, published_at, featured_rank FROM posts WHERE featured_rank IS NOT NULL ORDER BY featured_rank ASC
`

func (q *Queries) ListFeaturedPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listFeaturedPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.SoWhat,
			&i.Tags,
			&i.Version,
			&i.PublishedAt,
			&i.FeaturedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, slug, body, so_what, tags, version, published_at, featured_rank FROM posts ORDER BY published_at DESC, id ASC
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.SoWhat,
			&i.Tags,
			&i.Version,
			&i.PublishedAt,
			&i.FeaturedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsFiltered = `-- name: ListPostsFiltered :many
SELECT id, title, slug, body, so_what, tags, version, published_at, featured_rank, count(*) OVER() AS total_count FROM posts
WHERE ($1::timestamptz IS NULL OR published_at >= $1)
  AND ($2::timestamptz IS NULL OR published_at <= $2)
ORDER BY
  CASE WHEN $3::bool THEN published_at END ASC,
  CASE WHEN NOT $3::bool THEN published_at END DESC,
  id ASC
LIMIT $5 OFFSET $4
`

type ListPostsFilteredParams struct {
	FromDate   pgtype.Timestamptz
	ToDate     pgtype.Timestamptz
	SortOldest bool
	PageOffset int32
	PageLimit  int32
}

type ListPostsFilteredRow struct {
	ID           int64
	Title        string
	Slug         string
	Body         string
	SoWhat       string
	Tags         []string
	Version      int32
	PublishedAt  pgtype.Timestamptz
	FeaturedRank pgtype.Int4
	TotalCount   int64
}

func (q *Queries) ListPostsFiltered(ctx context.Context, arg ListPostsFilteredParams) ([]ListPostsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listPostsFiltered,
		arg.FromDate,
		arg.ToDate,
		arg.SortOldest,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsFilteredRow
	for rows.Next() {
		var i ListPostsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.SoWhat,
			&i.Tags,
			&i.Version,
			&i.PublishedAt,
			&i.FeaturedRank,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeaturedPost = `-- name: SetFeaturedPost :exec
UPDATE posts SET featured_rank = $1 WHERE id = $2
`

type SetFeaturedPostParams struct {
	FeaturedRank pgtype.Int4
	ID           int64
}

func (q *Queries) SetFeaturedPost(ctx context.Context, arg SetFeaturedPostParams) error {
	_, err := q.db.Exec(ctx, setFeaturedPost, arg.FeaturedRank, arg.ID)
	return err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $1, body = $2, so_what = $3, tags = $4, published_at = $5, version = version + 1
WHERE id = $6 AND version = $7
RETURNING id, title, slug, body, so_what, tags, version, published_at, featured_rank
`

type UpdatePostParams struct {
	Title       string
	Body        string
	SoWhat      string
	Tags        []string
	PublishedAt pgtype.Timestamptz
	ID          int64
	Version     int32
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Body,
		arg.SoWhat,
		arg.Tags,
		arg.PublishedAt,
		arg.ID,
		arg.Version,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.SoWhat,
		&i.Tags,
		&i.Version,
		&i.PublishedAt,
		&i.FeaturedRank,
	)
	return i, err
}
