// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFeaturedProjects = `-- name: ClearFeaturedProjects :exec
UPDATE projects SET featured_rank = NULL WHERE featured_rank IS NOT NULL
`

func (q *Queries) ClearFeaturedProjects(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearFeaturedProjects)
	return err
}

const deletePostProjects = `-- name: DeletePostProjects :exec
DELETE FROM post_projects WHERE post_id = $1
`

func (q *Queries) DeletePostProjects(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deletePostProjects, postID)
	return err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, slug, description, featured_rank FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.FeaturedRank,
	)
	return i, err
}

const getProjectsByIDs = `-- name: GetProjectsByIDs :many
SELECT id, name, slug, description, featured_rank FROM projects WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetProjectsByIDs(ctx context.Context, ids []int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsForPost = `-- name: GetProjectsForPost :many
SELECT projects.id, projects.name, projects.slug, projects.description, projects.featured_rank FROM projects
JOIN post_projects ON post_projects.project_id = projects.id
WHERE post_projects.post_id = $1
ORDER BY projects.name ASC
`

func (q *Queries) GetProjectsForPost(ctx context.Context, postID int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPostProject = `-- name: InsertPostProject :exec
INSERT INTO post_projects (post_id, project_id) VALUES ($1, $2)
`

type InsertPostProjectParams struct {
	PostID    int64
	ProjectID int64
}

func (q *Queries) InsertPostProject(ctx context.Context, arg InsertPostProjectParams) error {
	_, err := q.db.Exec(ctx, insertPostProject, arg.PostID, arg.ProjectID)
	return err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (name, slug, description)
VALUES ($1, $2, $3)
RETURNING id, name, slug, description, featured_rank
`

type InsertProjectParams struct {
	Name        string
	Slug        string
	Description string
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject, arg.Name, arg.Slug, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.FeaturedRank,
	)
	return i, err
}

const listFeaturedProjects = `-- name: ListFeaturedProjects :many
SELECT id, name, slug, description, featured_rank FROM projects WHERE featured_rank IS NOT NULL ORDER BY featured_rank ASC
`

func (q *Queries) ListFeaturedProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listFeaturedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByProjectSlug = `-- name: ListPostsByProjectSlug :many
SELECT posts.id, posts.title, posts.slug, posts.body, posts.so_what, posts.tags, posts.version, posts.published_at, posts.featured_rank FROM posts
JOIN post_projects ON post_projects.post_id = posts.id
JOIN projects ON post_projects.project_id = projects.id
WHERE projects.slug = $1
ORDER BY posts.published_at ASC, posts.id ASC
`

func (q *Queries) ListPostsByProjectSlug(ctx context.Context, slug string) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByProjectSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.SoWhat,
			&i.Tags,
			&i.Version,
			&i.PublishedAt,
			&i.FeaturedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, slug, description, featured_rank FROM projects ORDER BY name ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeaturedProject = `-- name: SetFeaturedProject :exec
UPDATE projects SET featured_rank = $1 WHERE id = $2
`

type SetFeaturedProjectParams struct {
	FeaturedRank pgtype.Int4
	ID           int64
}

func (q *Queries) SetFeaturedProject(ctx context.Context, arg SetFeaturedProjectParams) error {
	_, err := q.db.Exec(ctx, setFeaturedProject, arg.FeaturedRank, arg.ID)
	return err
}
