// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFeaturedProjects = `-- name: ClearFeaturedProjects :exec
UPDATE projects SET featured_rank = NULL WHERE featured_rank IS NOT NULL
`

func (q *Queries) ClearFeaturedProjects(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearFeaturedProjects)
	return err
}

const deletePostProjects = `-- name: DeletePostProjects :exec
DELETE FROM post_projects WHERE post_id = $1
`

func (q *Queries) DeletePostProjects(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deletePostProjects, postID)
	return err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1
`

// post_projects rows for this project cascade-delete (ON DELETE CASCADE on
// post_projects.project_id, see 00003_create_projects_tables.sql) — the
// posts themselves are untouched, only unlinked.
func (q *Queries) DeleteProject(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, slug, description, featured_rank, created_at, order_key FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.FeaturedRank,
		&i.CreatedAt,
		&i.OrderKey,
	)
	return i, err
}

const getProjectsByIDs = `-- name: GetProjectsByIDs :many
SELECT id, name, slug, description, featured_rank, created_at, order_key FROM projects WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetProjectsByIDs(ctx context.Context, ids []int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
			&i.CreatedAt,
			&i.OrderKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsForPost = `-- name: GetProjectsForPost :many
SELECT projects.id, projects.name, projects.slug, projects.description, projects.featured_rank, projects.created_at, projects.order_key FROM projects
JOIN post_projects ON post_projects.project_id = projects.id
WHERE post_projects.post_id = $1
ORDER BY projects.name ASC
`

func (q *Queries) GetProjectsForPost(ctx context.Context, postID int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
			&i.CreatedAt,
			&i.OrderKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPostProject = `-- name: InsertPostProject :exec
INSERT INTO post_projects (post_id, project_id) VALUES ($1, $2)
`

type InsertPostProjectParams struct {
	PostID    int64
	ProjectID int64
}

func (q *Queries) InsertPostProject(ctx context.Context, arg InsertPostProjectParams) error {
	_, err := q.db.Exec(ctx, insertPostProject, arg.PostID, arg.ProjectID)
	return err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (name, slug, description, created_at, order_key)
VALUES (
  $1, $2, $3,
  COALESCE($4::timestamptz, now()),
  COALESCE((SELECT MAX(order_key) FROM projects), 0) + 1
)
RETURNING id, name, slug, description, featured_rank, created_at, order_key
`

type InsertProjectParams struct {
	Name        string
	Slug        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

// order_key is never a caller-supplied value: it's computed here as one past
// the current maximum, so a new project always lands at the end of the
// curated order (see docs/adr/0006-project-ordering-via-editable-order-key.md).
func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.FeaturedRank,
		&i.CreatedAt,
		&i.OrderKey,
	)
	return i, err
}

const listFeaturedProjects = `-- name: ListFeaturedProjects :many
SELECT id, name, slug, description, featured_rank, created_at, order_key FROM projects WHERE featured_rank IS NOT NULL ORDER BY featured_rank ASC
`

func (q *Queries) ListFeaturedProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listFeaturedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
			&i.CreatedAt,
			&i.OrderKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByProjectSlug = `-- name: ListPostsByProjectSlug :many
SELECT posts.id, posts.title, posts.slug, posts.body, posts.so_what, posts.tags, posts.version, posts.published_at, posts.featured_rank FROM posts
JOIN post_projects ON post_projects.post_id = posts.id
JOIN projects ON post_projects.project_id = projects.id
WHERE projects.slug = $1
ORDER BY posts.published_at ASC, posts.id ASC
`

func (q *Queries) ListPostsByProjectSlug(ctx context.Context, slug string) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByProjectSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.SoWhat,
			&i.Tags,
			&i.Version,
			&i.PublishedAt,
			&i.FeaturedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, slug, description, featured_rank, created_at, order_key FROM projects ORDER BY name ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
			&i.CreatedAt,
			&i.OrderKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrder = `-- name: ListProjectsByOrder :many
SELECT id, name, slug, description, featured_rank, created_at, order_key FROM projects ORDER BY order_key ASC, id ASC
`

func (q *Queries) ListProjectsByOrder(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
			&i.CreatedAt,
			&i.OrderKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsFiltered = `-- name: ListProjectsFiltered :many
SELECT id, name, slug, description, featured_rank, created_at, order_key, count(*) OVER() AS total_count FROM projects
WHERE ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at <= $2)
ORDER BY
  CASE WHEN $3::text = 'curated' THEN order_key END ASC,
  CASE WHEN $3::text = 'oldest' THEN created_at END ASC,
  CASE WHEN $3::text = 'newest' THEN created_at END DESC,
  id ASC
LIMIT $5 OFFSET $4
`

type ListProjectsFilteredParams struct {
	FromDate   pgtype.Timestamptz
	ToDate     pgtype.Timestamptz
	SortMode   string
	PageOffset int32
	PageLimit  int32
}

type ListProjectsFilteredRow struct {
	ID           int64
	Name         string
	Slug         string
	Description  string
	FeaturedRank pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	OrderKey     float64
	TotalCount   int64
}

// sort_mode is one of "curated" (order_key ASC, the default), "newest", or
// "oldest" (both by created_at) — exactly one CASE branch is non-NULL for any
// given sort_mode, so it alone determines the effective order; id ASC is the
// final tie-break in all three modes.
func (q *Queries) ListProjectsFiltered(ctx context.Context, arg ListProjectsFilteredParams) ([]ListProjectsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listProjectsFiltered,
		arg.FromDate,
		arg.ToDate,
		arg.SortMode,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsFilteredRow
	for rows.Next() {
		var i ListProjectsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.FeaturedRank,
			&i.CreatedAt,
			&i.OrderKey,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeaturedProject = `-- name: SetFeaturedProject :exec
UPDATE projects SET featured_rank = $1 WHERE id = $2
`

type SetFeaturedProjectParams struct {
	FeaturedRank pgtype.Int4
	ID           int64
}

func (q *Queries) SetFeaturedProject(ctx context.Context, arg SetFeaturedProjectParams) error {
	_, err := q.db.Exec(ctx, setFeaturedProject, arg.FeaturedRank, arg.ID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET description = $1, order_key = $2, created_at = $3
WHERE id = $4
RETURNING id, name, slug, description, featured_rank, created_at, order_key
`

type UpdateProjectParams struct {
	Description string
	OrderKey    float64
	CreatedAt   pgtype.Timestamptz
	ID          int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Description,
		arg.OrderKey,
		arg.CreatedAt,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.FeaturedRank,
		&i.CreatedAt,
		&i.OrderKey,
	)
	return i, err
}

const updateProjectOrderKey = `-- name: UpdateProjectOrderKey :exec
UPDATE projects SET order_key = $1 WHERE id = $2
`

type UpdateProjectOrderKeyParams struct {
	OrderKey float64
	ID       int64
}

func (q *Queries) UpdateProjectOrderKey(ctx context.Context, arg UpdateProjectOrderKeyParams) error {
	_, err := q.db.Exec(ctx, updateProjectOrderKey, arg.OrderKey, arg.ID)
	return err
}
