// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package database

import (
	"context"
)

const deleteAllSkills = `-- name: DeleteAllSkills :exec
DELETE FROM skill
`

func (q *Queries) DeleteAllSkills(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllSkills)
	return err
}

const insertSkill = `-- name: InsertSkill :one
INSERT INTO skill (category, name, order_key) VALUES ($1, $2, $3) RETURNING id, category, name, order_key
`

type InsertSkillParams struct {
	Category string
	Name     string
	OrderKey float64
}

func (q *Queries) InsertSkill(ctx context.Context, arg InsertSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, insertSkill, arg.Category, arg.Name, arg.OrderKey)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Name,
		&i.OrderKey,
	)
	return i, err
}

const listSkillsByOrder = `-- name: ListSkillsByOrder :many
SELECT id, category, name, order_key FROM skill ORDER BY order_key ASC, id ASC
`

func (q *Queries) ListSkillsByOrder(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsByOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.OrderKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
